CREATE TABLE ARTICLES (ID BIGINT NOT NULL, NAME VARCHAR(255), PRICE NUMERIC(38), STOCK NUMERIC(10), PRIMARY KEY (ID));

CREATE TABLE ORDERS (ID BIGINT NOT NULL, CUSTOMERNAME VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE ORDERLINES (ID BIGINT NOT NULL, ORDER_ID BIGINT NOT NULL, ARTICLE_ID BIGINT NOT NULL, PRIMARY KEY (ID));

ALTER TABLE ORDERLINES ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID);

ALTER TABLE ORDERLINES ADD FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ID);

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));