INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

INSERT INTO ARTICLE (ID, NAME, PRICE, STOCK) VALUES (1, 'iPhone 7', 828, 5);
INSERT INTO ARTICLE (ID, NAME, PRICE, STOCK) VALUES (2, 'Samsung Galaxy S7', 924, 4);
INSERT INTO ARTICLE (ID, NAME, PRICE, STOCK) VALUES (3, 'Huawei P6', 668, 100);

UPDATE SEQUENCE SET SEQ_COUNT = 10 WHERE SEQ_NAME = 'SEQ_GEN';

