CREATE TABLE ACMEMESSAGE (ID BIGINT NOT NULL, MESSAGEID VARCHAR(255), TYPE VARCHAR(255), PAYLOAD VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE ARTICLE (ID BIGINT NOT NULL, NAME VARCHAR(255), PRICE NUMERIC(38), STOCK NUMERIC(10), PRIMARY KEY (ID));

CREATE TABLE "ORDER" (ID BIGINT NOT NULL, CUSTOMERNAME VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE ORDERLINE (ID BIGINT NOT NULL, ORDER_ID BIGINT NOT NULL, ARTICLE_ID BIGINT NOT NULL, PRIMARY KEY (ID));

ALTER TABLE ORDERLINE ADD FOREIGN KEY (ORDER_ID) REFERENCES "ORDER"(ID);

ALTER TABLE ORDERLINE ADD FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ID);

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));